package main

import (
	"fmt"
	"sort"
	"strings"
)

const defaultScanExtensionsConfig = ".go,.ts,.svelte,.js,.tsx,.jsx"

var configTemplateKnownKeys = map[string]bool{
	"board":           true,
	"prefix":          true,
	"wip_limit":       true,
	"scan_extensions": true,
}

func renderConfigTemplate(values map[string]string) []byte {
	boardPath := values["board"]
	if boardPath == "" {
		boardPath = "board"
	}
	prefix := values["prefix"]
	if prefix == "" {
		prefix = "PR"
	}

	var b strings.Builder
	b.WriteString("# tb project config\n")
	b.WriteString("# Generated by `tb init`; rerun `tb init` to refresh with .bak backups.\n\n")
	b.WriteString("# Board directory relative to this file.\n")
	fmt.Fprintf(&b, "board: %s\n\n", boardPath)
	b.WriteString("# Task ID prefix.\n")
	fmt.Fprintf(&b, "prefix: %s\n\n", prefix)
	b.WriteString("# Warn when starting a task above this many in-progress tasks.\n")
	writeOptionalConfigLine(&b, values, "wip_limit", "2")
	b.WriteString("\n")
	b.WriteString("# File extensions scanned by `tb scan`.\n")
	writeOptionalConfigLine(&b, values, "scan_extensions", defaultScanExtensionsConfig)

	var extraKeys []string
	for key := range values {
		if !configTemplateKnownKeys[key] {
			extraKeys = append(extraKeys, key)
		}
	}
	sort.Strings(extraKeys)
	if len(extraKeys) > 0 {
		b.WriteString("\n# Additional existing config fields preserved by `tb init`.\n")
		for _, key := range extraKeys {
			fmt.Fprintf(&b, "%s: %s\n", key, values[key])
		}
	}
	return []byte(b.String())
}

func writeOptionalConfigLine(b *strings.Builder, values map[string]string, key, defaultValue string) {
	if value := values[key]; value != "" {
		fmt.Fprintf(b, "%s: %s\n", key, value)
		return
	}
	fmt.Fprintf(b, "# %s: %s\n", key, defaultValue)
}
